<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.2.4" name="tile-map" tilewidth="8" tileheight="8" tilecount="400" columns="20">
 <image source="../tile-map.png" width="160" height="160"/>
 <tile id="20" type="solid"/>
 <tile id="21" type="solid"/>
 <tile id="22" type="solid"/>
 <tile id="23" type="solid"/>
 <tile id="24" type="solid"/>
 <tile id="25" type="solid"/>
 <tile id="26" type="solid"/>
 <tile id="27" type="solid"/>
 <tile id="28" type="solid"/>
 <tile id="29" type="solid"/>
 <tile id="40" type="solid"/>
 <tile id="41" type="solid"/>
 <tile id="42" type="solid"/>
 <tile id="43" type="solid"/>
 <tile id="44" type="solid"/>
 <tile id="45" type="solid"/>
 <tile id="46" type="solid"/>
 <tile id="47" type="solid"/>
 <tile id="48" type="solid"/>
 <tile id="49" type="solid"/>
 <tile id="80" type="solid"/>
 <tile id="81" type="solid"/>
 <tile id="82" type="solid"/>
 <tile id="84" type="solid"/>
 <tile id="85" type="solid"/>
 <tile id="86" type="solid"/>
 <tile id="87" type="solid"/>
 <tile id="88" type="solid"/>
 <tile id="89" type="solid"/>
 <tile id="90" type="solid"/>
 <tile id="91" type="solid"/>
 <tile id="92" type="solid"/>
 <tile id="93" type="solid"/>
 <tile id="94" type="solid"/>
 <tile id="95" type="solid"/>
 <tile id="96" type="solid"/>
 <tile id="97" type="solid"/>
 <tile id="100" type="solid"/>
 <tile id="101" type="solid"/>
 <tile id="102" type="solid"/>
 <tile id="113" type="solid"/>
 <tile id="114" type="solid"/>
 <tile id="115" type="solid"/>
 <tile id="116" type="solid"/>
 <tile id="120" type="solid"/>
 <tile id="121" type="solid"/>
 <tile id="122" type="solid"/>
 <tile id="133" type="solid"/>
 <tile id="134" type="solid"/>
 <tile id="135" type="solid"/>
 <tile id="136" type="solid"/>
 <tile id="153" type="solid"/>
 <tile id="154" type="solid"/>
 <tile id="155" type="solid"/>
 <tile id="156" type="solid"/>
</tileset>
